---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: control
  become: yes
  roles:
    - role: k3s/control

- hosts: node
  become: yes
  roles:
    - role: k3s/node
